export const RLABELS: Record<string, string> = {
  admin: 'Admin',
  designer: 'Designer',
  store_leather: 'Store - Leather',
  store_lining: 'Store - Lining',
  store_app: 'Store - App',
  store_bottom: 'Store - Bottom',
  lc: 'Leather Cutting Incharge',
  ln: 'Lining Cutting Incharge',
  last: 'Lasting Incharge',
  inj: 'Injection Incharge',
  director: 'Director',
  manager: 'Manager',
  customer: 'Customer'
};

export const CORE_OPS = [
  // Phase 1: Sample Request
  { id: 1, name: 'Pattern', phase: 1, defaultUser: 'designer' },
  { id: 2, name: 'Leather Arrangement', phase: 1, defaultUser: 'store_leather' },
  { id: 3, name: 'Lining Arrangement', phase: 1, defaultUser: 'store_lining' },
  { id: 4, name: 'Application Arrangement', phase: 1, defaultUser: 'store_app' },
  { id: 4.5, name: 'Bottom Arrangement', phase: 1, defaultUser: 'store_bottom' },
  { id: 5, name: 'Leather Cutting', phase: 1, defaultUser: 'lc' },
  { id: 6, name: 'Lining Cutting', phase: 1, defaultUser: 'ln' },
  { id: 7, name: 'Splitting', phase: 1, defaultUser: 'lc' },
  { id: 8, name: 'Skiving', phase: 1, defaultUser: 'lc' },
  { id: 9, name: 'Preparation for Closing', phase: 1, defaultUser: 'designer' },
  { id: 10, name: 'Closing', phase: 1, defaultUser: 'designer' },
  { id: 11, name: 'Eyelet / D-Ring', phase: 1, defaultUser: 'designer' },
  { id: 12, name: 'Counter Moulding', phase: 1, defaultUser: 'designer' },
  { id: 13, name: 'Strobell', phase: 1, defaultUser: 'designer' },
  { id: 14, name: 'Lasting', phase: 1, defaultUser: 'last' },
  { id: 15.1, name: 'Injection Desma', phase: 1, defaultUser: 'inj' },
  { id: 15.2, name: 'Injection Pouring', phase: 1, defaultUser: 'inj' },
  { id: 16, name: 'Finishing', phase: 1, defaultUser: 'designer' },
  { id: 17, name: 'Lacing', phase: 1, defaultUser: 'designer' },
  { id: 18, name: 'Insocks', phase: 1, defaultUser: 'inj' },
  { id: 19, name: 'Packing', phase: 1, defaultUser: 'designer' },
  { id: 20, name: 'Courier No. & Email to Customer', phase: 1, defaultUser: 'designer' },
  { id: 21, name: 'Costing Pattern', phase: 1, defaultUser: 'designer' },
  { id: 22, name: 'Waiting for Customer Comment', phase: 1, defaultUser: 'director' },
  { id: 23, name: 'Waiting for Approved Sample', phase: 1, defaultUser: 'admin' },
  { id: 24, name: 'Approved Sample Receiving Date', phase: 1, defaultUser: 'admin' },
  
  // Phase 2: Production Order
  { id: 25, name: 'First Order Receive', phase: 2, defaultUser: 'admin' },
  { id: 26, name: 'Grading', phase: 2, defaultUser: 'designer' },
  { id: 27, name: 'All Size Testing', phase: 2, defaultUser: 'designer' },
  { id: 28, name: 'Die Tooling', phase: 2, defaultUser: 'designer' },
  { id: 29, name: 'Send for Die Development', phase: 2, defaultUser: 'designer' },
  { id: 30, name: 'Receive & Die Check', phase: 2, defaultUser: 'designer' },
  { id: 31, name: 'Marking Pattern', phase: 2, defaultUser: 'designer' },
  { id: 32, name: 'Split & Skiving Spec', phase: 2, defaultUser: 'designer' },
  { id: 33, name: 'Toe Cap Breakup', phase: 2, defaultUser: 'designer' },
  { id: 34, name: 'Lace Breakup', phase: 2, defaultUser: 'designer' },
  { id: 35, name: 'TPU Breakup', phase: 2, defaultUser: 'designer' },
  { id: 36, name: 'Approval of Size Label', phase: 2, defaultUser: 'designer' },
  { id: 37, name: 'Complete Specifications', phase: 2, defaultUser: 'designer' },
  { id: 38, name: 'Box, Carton & Packing Detail', phase: 2, defaultUser: 'designer' },

  // Phase 3: Bulk Production
  { id: 39, name: 'Purchase - Leather', phase: 3, defaultUser: 'bp_purch_leather' },
  { id: 40, name: 'Purchase - Lining', phase: 3, defaultUser: 'bp_purch_lining' },
  { id: 41, name: 'Purchase - Toecap/Midplate/Box', phase: 3, defaultUser: 'bp_purch_other' },
  { id: 42, name: 'Cutting - Leather/Split/Skive', phase: 3, defaultUser: 'bp_cut_leather' },
  { id: 43, name: 'Cutting - Lining', phase: 3, defaultUser: 'bp_cut_lining' },
  { id: 44, name: 'Preparing - Paste/Label/Seam', phase: 3, defaultUser: 'bp_prepare' },
  { id: 45, name: 'Closing', phase: 3, defaultUser: 'bp_closing' },
  { id: 46, name: 'Upper Pass', phase: 3, defaultUser: 'bp_upper_pass' },
  { id: 47, name: 'Lasting', phase: 3, defaultUser: 'bp_lasting' },
  { id: 48, name: 'LT Pass', phase: 3, defaultUser: 'bp_lt_pass' },
  { id: 49, name: 'Injection Desma', phase: 3, defaultUser: 'bp_inj_desma' },
  { id: 50, name: 'Injection Pouring', phase: 3, defaultUser: 'bp_inj_pouring' },
  { id: 51, name: 'Final Passing & Packing', phase: 3, defaultUser: 'bp_final_pack' }
];
