import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  themeColor: "#2563eb",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // Prevents zooming on mobile inputs
};

export const metadata: Metadata = {
  title: "SR Footwear ERP",
  description: "Dedicated Factory Management Engine",
  manifest: "/manifest.json", // This will be auto-generated by our manifest.ts or next-pwa
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "SR ERP",
  },
  formatDetection: {
    telephone: false,
  },
};

import { PwaRegister } from "@/components/PwaRegister";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50 text-slate-900 antialiased`}>
        <PwaRegister />
        {children}
      </body>
    </html>
  );
}
